#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @import rlang
#' @importFrom dplyr across
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr if_else
#' @importFrom dplyr inner_join
#' @importFrom dplyr lag
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr row_number
#' @importFrom dplyr select
#' @importFrom dplyr starts_with
#' @importFrom dplyr summarize
#' @importFrom dplyr ungroup
#' @importFrom dplyr where
#' @importFrom glue glue
#' @importFrom janitor clean_names
#' @importFrom lifecycle deprecated
#' @importFrom lubridate %within%
#' @importFrom lubridate as_date
#' @importFrom lubridate duration
#' @importFrom lubridate interval
#' @importFrom lubridate NA_POSIXct_
#' @importFrom magrittr %>%
#' @importFrom readr col_character
#' @importFrom readr col_date
#' @importFrom readr col_datetime
#' @importFrom readr col_double
#' @importFrom readr col_factor
#' @importFrom readr col_guess
#' @importFrom readr col_integer
#' @importFrom readr col_logical
#' @importFrom readr col_number
#' @importFrom readr col_skip
#' @importFrom readr col_time
#' @importFrom readr cols
#' @importFrom readr read_delim
#' @importFrom stringr str_detect
#' @importFrom stringr str_extract
#' @importFrom stringr str_match
#' @importFrom stringr str_remove_all
#' @importFrom stringr str_replace
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_squish
#' @importFrom stringr str_to_lower
#' @importFrom stringr str_trim
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr separate_wider_delim
## usethis namespace: end
NULL
